language: node_js
node_js:
  - "7"

install:
  - npm install
  - npm test

notifications:
  irc:
    channels:
      - "chat.freenode.net#cibot"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
  webhooks:
    urls:
      - https://98e784af.ngrok.io/build
