language: node_js
node_js:
  - "7"

install:
  - npm install
  - npm test

notifications:
  irc:
    channels:
      - "chat.freenode.net#cibot"
    template:
          - "%{message}"
  webhooks:
    urls:
      - http://825310a4.ngrok.io/build
