language: node_js
node_js:
  - "7"

install:
  - npm install
  - npm test

notifications:
  irc:
    channels:
      - "chat.freenode.net#cibot"
  webhooks:
    urls:
      - http://1e69044d.ngrok.io/build
template:
      - "%{message}"
